### PR TITLE
Update test-independent-test_utils_cli.R

### PR DESCRIPTION
**Pull request by nanxstats**
This PR adds indenpendent unit tests for the utilitity functions that replaced cli.

### CODE REVIEW

**Comment by elong0527** [comment]
Shall we fix the windows check before merging?

**Comment by nanxstats** [comment]
Yes, I guess @DanfengFu will look into the Windows-specific testing issue.

**Comment by nanxstats** [comment]
It appears that the Unicode bullet point character in `cli_li()` is not working when running R under Windows console (command prompt), but works ok in the RStudio console.

```r
> pkglite:::cli_li("zzz")
 zzz
```

Also considering the situation of Windows support for Unicode characters:
https://developer.r-project.org/Blog/public/2020/07/30/windows/utf-8-build-of-r-and-cran-packages/

Maybe these are the reasons why the test is only failing under Windows.

I've decided to use a simple hyphen (`-`), which is also copy-paste-able as Markdown, as the bullet point character there.

**Comment by nanxstats** [comment]
I will merge this PR first. Then I'll fix the original implementation with the test. This is a great find! Thanks again. @DanfengFu

**Pull request merged**
